version: "3.9"
services:
  web:
    build:
      context: ./pointr
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./pointr:/app
    env_file:
      - pointr/.env
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pointr
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend: